### ISSUE TITLE
Como Visitante, al entrar a la sección de /Home, puedo ver una descripción breve de los ámbitos en los que se desarrolla el equipo.

### ISSUE THREAD

**Issue by gallosanchez23** [gallosanchez23/roborregos-web#28]
- Como Visitante, al entrar a la sección de /Home, puedo ver una descripción breve de los ámbitos en los que se desarrolla el equipo.

**Comportamiento deseado**
- Cuando entro a /Home, puedo ver una sección informativa dividida en 4 partes:
  - Competencias internacionales
  - Proyectos sociales
  - Colaboraciones profesionales
  - Comunidad estudiantil
- En cada una de estas secciones puedo ver una breve descripción de cómo se desarrolla el equipo dentro de estos ámbitos

**Notas adicionales**
- En dado caso, es posible cambiar estas secciones o agregar algún ámbito que se considere más relevante para el equipo.

**Criterios de aceptación**
- [ ] En la sección informativa se encuentran al menos 4 divisiones con información atractiva al lector y vigente para el equipo.
- [ ] La sección informativa es responsiva.

**Comment by AuroTB** [comment]
There is already an implementation of this,
please check the pull request of **home_content**
![image](https://user-images.githubusercontent.com/25405578/75188461-caff2200-5711-11ea-95f4-da822d18747c.png)
![image](https://user-images.githubusercontent.com/25405578/75188487-d5212080-5711-11ea-93c4-e508b3e2d62a.png)
![image](https://user-images.githubusercontent.com/25405578/75188521-e0744c00-5711-11ea-9699-a2497a6549b0.png)
![image](https://user-images.githubusercontent.com/25405578/75188547-e9651d80-5711-11ea-92b3-15eea8586891.png)
