### ISSUE TITLE
Como Visitante, al entrar a la sección de /Home, puedo ver imágenes de fondo relacionadas con el equipo y/o tecnología.

### ISSUE THREAD

**Issue by gallosanchez23** [gallosanchez23/roborregos-web#30]
- Como Visitante, al entrar a la sección de /Home, puedo ver imágenes de fondo relacionadas con el equipo y/o tecnología.

**Comportamiento deseado**
- Cuando entro a /Home, todas las secciones tienen imágenes de fondo relacionadas con el equipo o lo que se hace dentro de.
- Todas las imágenes de fondo siguen el mismo partón de diseño.

**Criterios de aceptación**
- [ ] Todas las imágenes siguen el mismo patrón de diseño.
- [ ] Todas las imágenes son relacionadas con el equipo.
- [ ] Todas las imágenes se comportan de forma responsiva.

**Comment by AuroTB** [comment]
There is already an implementation of this,
please check the pull request of home_content.

(screenshots in issue #28 )
