### ISSUE TITLE
Como Visitante, al entrar a cualquier extensión del sitio, puedo ver una navigation bar responsiva.

### ISSUE THREAD

**Issue by gallosanchez23** [gallosanchez23/roborregos-web#31]
- Como Visitante, al entrar a cualquier extensión del sitio, puedo ver una navigation bar responsiva con ligas a las extensiones principales.

**Comportamiento deseado**
- En cualquier momento dentro del sitio, debo poder ver una navigatiton bar con los links a las extensiones principales del sitio.
- Es muy importante que la navigation bar se comporte de forma responsive.

**Criterios de aceptación**
- [x] La navigation debe estar posisionada de forma fixed en la parte superior de la pantalla.
- [x] La navigation bar se debe de comportar de forma responsiva.
- [x] La navigation bar debe seguir los patrones de diseño del sitio.
- [x] La navigation bar debe de tener links a las principales extensiones del sitio.

**Comment by AuroTB** [comment]
me gustaba más como se veía con color naranja jajaja
