### ISSUE TITLE
Como Visitante, al entrar en la sección de /Members y seleccionar uno desde la grid, puedo ver una breve presentación y su información de contacto.

### ISSUE THREAD

**Issue by gallosanchez23** [gallosanchez23/roborregos-web#33]
- Como Visitante, al entrar en la sección de /Members y seleccionar uno desde la grid, puedo ver una breve presentación y su información de contacto.

**Comportamiento deseado**
- Al entrar a la extensión de /Members existe una sección de grid con todos los miembros.
- Al seleccionar a uno de los miembros del equipo se abre un modal.
- Dentro del modal hay una imagen del miembro seleccionado, una breve descripción y su información de contacto.

**Criterios de aceptación**
- [x] El modal se comporta de forma responsiva.
- [x] El modal contiene la misma imagen de la grid.
- [x] El modal contiene una breve descripción del miembro donde se describe quién es, qué ha hecho dentro del equipo, inereses personales, etc.
- [ ] El modal contiene la información de contacto de la persona: Github, Linkedin, Resume, Correo electrónico.
- [ ] Los elementos dentro de la información de contacto son links a las diferentes redes sociales (Github y Linkedin), descarga de archivo (Resume) y liga para envío de correo (email).

**Comment by gallosanchez23** [comment]
@Josecisneros001 comúnicate con @AuroTB por favor, ella había hecho un google forms para recabar esta información de los miembros del equipo. Los resultados de ese forms te deben facilitar la info. Igualmente, para los íconos estámos utilizando material-ui.

**Comment by AuroTB** [comment]
cámbialo a 3 estrellas porque nmms

**Comment by AuroTB** [comment]
Siento que lo de obtener todos los datos y agregarlos a cada uno tiene que ver más con contenido.

**Comment by AuroTB** [comment]
large view:
![image](https://user-images.githubusercontent.com/25405578/77257910-d8d69300-6c3c-11ea-9eaf-ac913b9bddf5.png)
small device view:
![image](https://user-images.githubusercontent.com/25405578/77257924-f146ad80-6c3c-11ea-9beb-8bba35fab4a4.png)
(lo probé con todos los devicen en "inspeccionar" de chrome.

Cosas por hacer de contenido (que creo que deberían de ponerse en un issue de contenido:
-Obtener los datos de github, linkedin, o lo que quieran poner
-Hacer que las fotos estén centradas (porque luego se ven raro en los small devices)
-Modificar JSON para esa info que falta (eso lo puedo hacer yo con dummy data por ahora)

Cosas por hacer de UI devel:
-Posicionar despliegue de links (git, linkedin) en las dos vistas (large y small)
-Responsivity

Notas: El issue #44 creo que depende mucho de esto, porque también estaba pensando en agregar un atributo al JSON llamado "estatus" que sea un simple booleano de si está activo o inactivo (activo: dentro del equipo, inactivo: fuera del equipo).

¿Qué opinas?

**Comment by gallosanchez23** [comment]
@AuroTB algunos puntos:
- Me parece buena idea, ahora que tenemos equipo de contenido, el juntar la información de los miembros del equipo podría quedar en otro issue. Lo voy a quitar de este issue, gracias.
- Por ahora te puedo aceptar un pr con información dummy, pero por favor que los links ya estén funcionando.
- Igualmente, es parte del issue que el modal quede al 100, lo que incluye una imagn centrada para el tamaño mobile, etc.
- Cambiaré el issue a 2 estrellas. Considero que es un feature, sí, un tanto más complicado por la cuestión del responsivity del modal, pero no al nivel de un _high effort_.

**Comment by AuroTB** [comment]
Hey, acerca de que "el modal quede al 100, lo que incluye una imagen centrada para el tamaño mobile, etc." depende mucho de la foto:
![image](https://user-images.githubusercontent.com/25405578/78713337-bbadef80-78df-11ea-8540-8078897bee23.png)
![image](https://user-images.githubusercontent.com/25405578/78713355-c6688480-78df-11ea-8886-f5ab9876acfb.png)

Se puede resolver de las sig maneras:
- poniendo un atributo en el json especificando el centro de la fotografía y hardcodeando una función para moverla de acuerdo al centro
- haciendo que contenido se encargue de que la fotografía esté centrada

No se qué creas que sea mejor, me avisas.
