### ISSUE TITLE
Como Visitante, al entrar en la sección de /Members, puedo ver una sección con un botón para interesados en candidates.

### ISSUE THREAD

**Issue by gallosanchez23** [gallosanchez23/roborregos-web#34]
- Como Visitante, al entrar en la sección de /Members, puedo ver una sección con un botón para interesados en candidates.

**Comportamiento deseado**
- Al entrar en la sección de /Members existe una sección al final de la página dedicada a interesados en unirse al equipo.
- Dentro de esta sección existe una frase de invitación.
- Dentro de esta sección existe un botón que redirecciona a la extención de /Contact#Candidates

**Criterios de aceptación**
- [x] La sección se comporta de forma responsiva.
- [x] La sección sigue los patrones de diseño y estilo del sitio.
- [x] La sección contiene un botón que redirecciona a /JoinUs#Candidates.
- [x] La sección contiene una leyenda como invitación a unirse al equipo.

**Comment by AuroTB** [comment]
There already is a button (and some other features) implemented in the members-page branch.
Please check the pull request.
![image](https://user-images.githubusercontent.com/25405578/75188184-4ad8bc80-5711-11ea-9185-fabea1f72723.png)

**Comment by AuroTB** [comment]
Updated responsivity, check it out!
