### ISSUE TITLE
Como Visitante, en la sección de /Members#grid, veo dos secciones para miembros activos y alumni.

### ISSUE THREAD

**Issue by gallosanchez23** [gallosanchez23/roborregos-web#44]
- Como Visitante, al entrar a la sección de /Members, en la sección de la grid, puedo ver una división señalada para los miembros históricos y otra con los acutales.

**Comportamiento deseado**
- Al entrar en la sección pública de /Members, existe una sección después del header que contiene una grid mostrando todos los miembros del equipo.
- Dentro de esta grid existe una división entre los miembros históricos y los miembros actuales del equipo.
- Se muestran primeramente los miembros actuales y posteriormente los miembros históricos.

**Criterios de aceptación**
- [x] Esta sección sigue el diseños presentado en [invision](https://claragutierrez948964.invisionapp.com/prototype/roborregos-web-design-ck7wek80a00nuq301lmd3k920/play/ce14019d?linkshare=urlcopied&v=XoVNrhIoXMb%2B31odiZpcZQ%3D%3D).
- [x] Los miembros mostrados en la grid son extraidos desde el json correspondiente a Members.
- [x] Los miembros presentados en la grid están ordenados con respecto a su aparición en el json.
- [x] La grid se comporta de forma responsiva según lo presentado en [invision](https://claragutierrez948964.invisionapp.com/prototype/roborregos-web-responsive-ck7mj0dpn005tp701qnr2tnsu/play/39483fc7?linkshare=urlcopied&v=XoVNrhIoXMb%2B31odiZpcZQ%3D%3D).

**Comment by gallosanchez23** [comment]
@AuroTB la referencia de la división: https://claragutierrez948964.invisionapp.com/prototype/roborregos-web-design-ck7wek80a00nuq301lmd3k920/play/bc99c5f5?v=XoVNrhIoXMb%2B31odiZpcZQ%3D%3D&linkshare=urlcopied

**Comment by AuroTB** [comment]
Vistas finalizadas:
![image](https://user-images.githubusercontent.com/25405578/80787151-4a163980-8b4b-11ea-838d-359bdcbf3a45.png)
![image](https://user-images.githubusercontent.com/25405578/80787219-9792a680-8b4b-11ea-96ef-e5479c23572f.png)
![image](https://user-images.githubusercontent.com/25405578/80787253-abd6a380-8b4b-11ea-8930-e3e336c246d3.png)

**Comment by AuroTB** [comment]
Agregaría igual la prioridad en la que deben de desplegarse los miembros (de más antiguo a más reciente para miembros actuales y de más actuales a antiguos para los de legacy).
