### ISSUE TITLE
Como Visitante, al seleccionar un miembro inactivo de la grid, veo un modal con su info.

### ISSUE THREAD

**Issue by gallosanchez23** [gallosanchez23/roborregos-web#45]
**Comportamiento deseado**
- Al entrar en la sección de /Members#grid, y seleccionar un miembro de la sección de alumni, se abre un modal.
- En este modal hay un breve resumen del miembro, incluyendo nombre, período de actividad, área, descripción, info de contacto, etc.

**Criterios de aceptación**
- [x] Cuando selecciono un miembro inactivo de la grid, se abre un modal.
- [x] El modal sigue el diseño de [invision](https://claragutierrez948964.invisionapp.com/prototype/roborregos-web-design-ck7wek80a00nuq301lmd3k920/play/b5e716ab?v=XoVNrhIoXMb%2B31odiZpcZQ%3D%3D&linkshare=urlcopied).
- [x] El modal contiene información extraída del json correspondiente a Members.
- [x] La información del modal corresponde a la del miembro seleccionado.
- [x] La foto del modal es la misma que la de la grid.
- [x] El modal se comporta de forma responsiva según el diseño en [invision](https://claragutierrez948964.invisionapp.com/prototype/roborregos-web-responsive-ck7mj0dpn005tp701qnr2tnsu/play/22aede6e?v=XoVNrhIoXMb%2B31odiZpcZQ%3D%3D&linkshare=urlcopied).
- [x] Es posible cerrar el modal dando click en esc o en la tacha.

**Comment by AuroTB** [comment]
Este issue tiene tiene los mismos objetivos que el issue #33

**Comment by AuroTB** [comment]
Este issue depende del issue #44 y se realizará después de que se finalice con el otro.
