### ISSUE TITLE
Como Visitante, cuando entro a cualquier lugar del sitio, puedo ver el mismo footer al final de la página.

### ISSUE THREAD

**Issue by gallosanchez23** [gallosanchez23/roborregos-web#50]
- Como Visitante, cuando entro a cualquier lugar del sitio, puedo ver el mismo footer al final de la página.
- Modularización del Footer como un solo componente

**Comportamiento deseado**
- Cuando visito cualquier ligar del sitio, puedo ver el mismo footer al final de la página.
- El footer contiene una breve descripción de lo que es roborregos, un site map con las secciones principales, el aviso de copyright y enlaces a las redes sociales del equipo.

**Criterios de aceptación**
- [x] El footer contiene una breve descripción o referencia al equipo.
- [x] El footer contiene un site map con únicamente las secciones principales.
- [x] El footer contiene un mensaje de copyright.
- [x] El footer contiene enlaces a las redes del equipo con íconos: facebook, email, instagram, github
- [x] El footer se comporta de forma responsiva.
- [ ] El footer sigue los patrones de diseño del sitio.
- [x] El footer es único para cualquer lugar del sitio (el mismo `ReactComponent`).

**Comment by AuroTB** [comment]
Revisé con clara el diseño responsivo, todo cool!
