### ISSUE TITLE
Como Visitante, puedo ver el ícono del logotipo de roborregos en el tíulo del tab en el navegador.

### ISSUE THREAD

**Issue by gallosanchez23** [gallosanchez23/roborregos-web#64]
- Como Visitante, puedo ver el ícono del logotipo de roborregos en el tíulo del tab en el navegador.

**Comportamiento deseado**
- Actualmetne el ícono que se muestra en el título de la tab en el navegador es el default de una react app.
- Esto se debe modificar para que el ícono sea el de roborregos.

**Criterios de aceptación**
- [x] Al entrar en el sitio, el ícono que se muestra en el título de la tab del navegador, es el logotipo de roborregos.

**Comment by tomvik** [comment]
Creo que esto ya esta funcionando, no tengo que hacer algun cambio.

**Comment by tomvik** [comment]
![image](https://user-images.githubusercontent.com/13770244/77947773-a868a780-7281-11ea-87e5-370fac23c9d2.png)
![image](https://user-images.githubusercontent.com/13770244/77947805-b0c0e280-7281-11ea-91a4-77cc38317525.png)
