### ISSUE TITLE
Hacer deploy de la aplicación actual a Heroku.

### ISSUE THREAD

**Issue by gallosanchez23** [gallosanchez23/roborregos-web#67]
- Hacer deploy de la aplicación actual a Heroku.

**Comportamiento deseado**
- La aplicación actual del proyecto debe estar funcionando en línea dentro de un servidor de Heroku.

**Criterios de aceptación**
- [x] La aplicación funciona bajo un dominio de Heroku.
- [x] La aplicación está alojada en un servidor de Heroku.
- [x] Lo que está desplegado en producción correponde al contenido actual de la branch master.

**Comment by RicardoChapaRomero** [comment]
No es posible desplegar a master a menos que lo hagas directamente desde Heroku o hagas el merge de este issue a develop y de develop a master
