### ISSUE TITLE
Como Visitante, al seleccionar un miembro activo de la grid, veo un modal con su info.

### ISSUE THREAD

**Issue by gallosanchez23** [gallosanchez23/roborregos-web#87]
- Como Visitante, al seleccionar un miembro de la grid, veo un modal con su info.

**Comportamiento deseado**
- Estando en la vista de /Members, cuando selecciono un cuadrop de los miembros del equipo activo, se abre un modal con su información personal.
- En este modal puedo ver una breve descripción y del miembro que seleccioné, foto, nombre, e info de contacto.

**Criterios de aceptación**
- [x] Cuando selecciono un miembro de la grid, se abre un modal.
- [x] El modal sigue el diseño de [invision](https://claragutierrez948964.invisionapp.com/prototype/roborregos-web-design-ck7wek80a00nuq301lmd3k920/play/e2ca972f?linkshare=urlcopied&v=XoVNrhIoXMb%2B31odiZpcZQ%3D%3D).
- [x] El modal contiene información extraída del json correspondiente a Members.
- [x] La información del modal corresponde a la del miembro seleccionado.
- [x] La foto del modal es la misma que la de la grid.
- [x] El modal se comporta de forma responsiva según el diseño en [invision](https://claragutierrez948964.invisionapp.com/prototype/roborregos-web-responsive-ck7mj0dpn005tp701qnr2tnsu/play/a14bf593?linkshare=urlcopied&v=XoVNrhIoXMb%2B31odiZpcZQ%3D%3D).
- [x] Es posible cerrar el modal dando click en esc o en la tacha.
- [x] La información de contacto se muestra solo si está incuida en el json.

**Comment by AuroTB** [comment]
También quisiera agregar como un criterio que se valide la información desplegada (github, linedin y cv) y en caso de que la base de datos no la tenga no se desplieguen sus respectivos íconos.
![image](https://user-images.githubusercontent.com/25405578/79935290-2b60c600-841a-11ea-89ff-c813711a5703.png)

**Comment by gallosanchez23** [comment]
@AuroTB me parece bien, puedes agregar un conditional renderig, te lo agrego como criterio de aceptación. Gracias por la observación.
